//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace otomasyon2yedek
{
    using System;
    using System.Collections.Generic;
    
    public partial class adminler
    {
        public int adminid { get; set; }
        public string adminad { get; set; }
        public string adminsifre { get; set; }
    }
}
